apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-issuer-components
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    path: registry/clusters/dj-test/cert-issuers
    repoURL: https://github.com/jarededwards/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
