apiVersion: batch/v1
kind: Job
metadata:
  name: vault-handler
  namespace: vault
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    spec:
      containers:
      - args:
        - unseal
        image: eb129/vault-handler:v0
        imagePullPolicy: Always
        name: vault-handler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vault-handler
      serviceAccountName: vault-handler
      terminationGracePeriodSeconds: 30



